# Generated by Django 5.0.6 on 2024-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the publisher', max_length=50)),
                ('website', models.URLField(help_text='the website of the publisher')),
                ('email', models.EmailField(help_text='the email of the publisher', max_length=254)),
            ],
        ),
    ]
