# Generated by Django 5.0.6 on 2024-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the book', max_length=50)),
                ('publication_date', models.DateField(verbose_name='date the book was published')),
                ('isbn', models.CharField(max_length=50, verbose_name='the isbn number of books')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name of the contributors', max_length=20)),
                ('last_name', models.CharField(help_text='last name of the contributors', max_length=20)),
                ('email', models.EmailField(help_text='email of the contributors', max_length=254)),
            ],
        ),
    ]
