# Generated by Django 5.0.6 on 2024-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='first_names',
            field=models.CharField(help_text="The contributor's firstname or names.", max_length=50),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='last_names',
            field=models.CharField(help_text="The contributor's lastname or names.", max_length=50),
        ),
    ]
