# Generated by Django 5.0.6 on 2024-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=50)),
                ('creation_time', models.DateTimeField(auto_now_add=True, help_text='Project creation time.')),
                ('completion_time', models.DateTimeField(help_text='Project completion time', null=True)),
            ],
        ),
    ]
