# Generated by Django 5.0.6 on 2024-06-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=100)),
                ('description', models.TextField(help_text='Task description')),
                ('time_estimate', models.IntegerField(help_text='Time in hours required to complete the task.')),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectm.project')),
            ],
        ),
    ]
